# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.2.dev8+g47e365f.d20230710'
__version_tuple__ = version_tuple = (0, 2, 'dev8', 'g47e365f.d20230710')
