# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.2.dev10+g48c663b.d20230822'
__version_tuple__ = version_tuple = (0, 2, 'dev10', 'g48c663b.d20230822')
