name: combined_fit
channels:
  - defaults
  - conda-forge  
dependencies:
  - astropy
  - matplotlib
  - numpy
  - pandas
  - python>=3.9
  - scipy
  - iminuit
  - jupyterlab
  - setuptools
  - numba
