name: micro_combined_fit_test
channels:
  - defaults
  - conda-forge
dependencies:
  - astropy>=5.3.1
  - matplotlib
  - numpy
  - pandas
  - python>=3.9
  - scipy>=1.5
  - iminuit
  - jupyterlab
  - setuptools
  - numba
  - zstandard
  - tqdm
  - healpy
  - nomkl
